### PR TITLE
Upgrade ThemeComponents/NavItem to Angular

### LINKED ISSUE #2801: Upgrade ThemeComponents/NavItem to Angular component
Upgrade the component to Angular, and downgrade to AngularJS so that it can be used in the AngularJS pages.

### PR DESCRIPTION
**Pull request by breity**
Upgraded the component to Angular, downgrade to AngularJS so that it can be used in the AngularJS pages. Also de-coupled styling from AngularJS styles.

To test:
- Make sure nav items in unit plan (VLE) appear correctly, are styled.
- Make sure node icons all show up and are styled correctly across the apps (VLE, CM, AT).

Close #2801.

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
The general functionality works well. I found some minor styling issues noted below.

Sometimes in the "Unit Plan" view an activity/group will display as a long narrow column instead of taking taking up almost all the width of the window like it used to.

Screenshot 2020-12-01 124657

The rubric icons are slightly misaligned vertically due to the line-height: 24px style.

Screenshot 2020-12-01 145414

**Comment by breity** [comment]
@geoffreykwan Thanks for the bug reports. Those should be fixed now.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by hirokiterashima — APPROVED** [review]
Looks good.

**Pull request merged**
