### PR TITLE
Combine milestone reports

### LINKED ISSUE #2896: Combine milestone reports
Show before/after graphs and/or data plus student responses on one report.

[needs discussion]

### PR DESCRIPTION
**Pull request by geoffreykwan**
Make sure a milestone with one location still works like before.
Make sure a milestone with two locations shows the graph data for both components (locations).

Closes #2896

### CODE REVIEW

**Review by hirokiterashima — CHANGES_REQUESTED** [review]
I cleaned up some code. The reports are working for single and multiple components.

I noticed that the milestone-report-data component is throwing errors now because of the new aggregate object format.

E.g., if the matched template contains milestone-report-data elements like this:
```
<p><milestone-report-data score-id="ki" calc="percent" score-values="[5]"></milestone-report-data> of students scored 5 for KI.</p><p><milestone-report-data score-id="science" calc="percent" score-values="[3]"></milestone-report-data> of students scored 3 for science.</p><p><milestone-report-data score-id="experimentation" calc="count" score-values="[1,2]"></milestone-report-data> student(s) scored 2 or lower for experimentation.</p><p><milestone-report-data score-id="ki" calc="count"></milestone-report-data> student(s) have submitted an answer.</p>
```

Then the js console will throw an error like this:
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at MilestoneReportDataComponent.getScoreValuesCount (milestone-report-data.component.ts:52)
    at MilestoneReportDataComponent.getCount (milestone-report-data.component.ts:45)
    at MilestoneReportDataComponent.getPercent (milestone-report-data.component.ts:38)
    at MilestoneReportDataComponent.ngOnInit (milestone-report-data.component.ts:27)
```

**Comment by geoffreykwan** [comment]
I fixed the problem with milestone-report-data throwing an error. You can also now specify a node-id and component-id for the milestone-report-data to display like this

```<p><milestone-report-data score-id="science" calc="average" node-id="node1" component-id="5fvck6nw4l"></milestone-report-data> is the average score for science on node1-5fvck6nw4l.</p>```

**Review by hirokiterashima — APPROVED** [review]
Problem is fixed.

**Review by breity — APPROVED** [review]
Looks good, MilestoneReportData is fixed.

**Pull request merged**
