### PR TITLE
Replace Summernote with TinyMCE

### LINKED ISSUE #2809: Replace Summernote with TinyMCE in html authoring and rubric authoring
### Description

- Replace the rubric authoring editor in the project, step, and component rubrics
- Replace the html authoring editor in the HTML component
- Make sure Insert WISE Asset still works
- Make sure Insert WISE Link still works

### LINKED ISSUE #2817: Replace Summernote with TinyMCE in Notebook Report and Notebook authoring
- Replace the Notebook Report editor for the teacher and student
- Replace the Notebook Report starter content authoring editor
- Implement inserting a Note into the Report with TinyMCE
- Remove all references to Summernote

### PR DESCRIPTION
**Pull request by geoffreykwan**
Things to test
- HTML authoring (including Insert WISE Asset and Insert WISE Link)
- Rubric authoring (for project, step, and components)
- Notebook Report starter content for teacher and student
- Teacher report
- Student report
- Student report inserting a note
- Report save time
- Make sure there are no more Summernote files and no more references to Summernote in the code

See if we want to add or remove some TinyMCE plugins
  - Here's a [demo page](https://www.tiny.cloud/docs/demo/full-featured/)
  - Here's the [plugin page](https://www.tiny.cloud/apps/)

Closes #2809
Closes #2817

### CODE REVIEW

**Review by breity — APPROVED** [review]
Working great! I made a bunch of UI/functionality updates, @hirokiterashima and I got productions builds to properly load site styles in TinyMCE. Will approve and re-request reviews.

To test:
- Run `npm install` to get latest dependencies.
- Test both dev and prod builds to make sure everything is working.

A summary of the changes I made:
- Removed Bootstrap dependency
- Updated toolbar and menu items + layout
- Matched editor and WISE styles
- Integrated WISE asset browse with TinyMCE image, media, link plugins
- Added default alt attribute to inserted WISE asset images
- Added custom icon for insert wiselink button
- Enabled and styled image captions, matched with insert note styles
- Added i18n in code entries

**Review by hirokiterashima — APPROVED** [review]
Looks good!

**Comment by geoffreykwan** [comment]
I've added WISE asset popup file type filtering. Here are things to test in the Authoring Tool.
- If you open up the WISE asset popup from the TinyMCE "Insert Image" button, make sure it only shows images
- If you open up the WISE asset popup from the TinyMCE "Insert Media" button, make sure it only shows audio or video files
- If you open up the WISE File Manager from the left toolbar in the Authoring Tool, all the files should be shown

The "Source" button doesn't do anything in the TinyMCE editor within the teacher and student report.
- Open the report
- Click the "Insert" button
- Click "Image..."
- Click the "Source" button
- Nothing happens since we don't have anywhere to grab assets from when in the Report context
Should we hide the "Source" button in the report?

The tests now also run *.spec.ts files from within the wise5 folder.

**Review by breity — APPROVED** [review]
Looks great. Filtering by file type for Insert Media/Image/Link works well. I'm approving now.

@geoffreykwan I agree that we should remove the Source link for reports/teacher notebook, since it doesn't do anything now. We could maybe hook in to student assets in the future if student uploads are allowed in the unit. Could also think about letting teachers upload files from their computer to include in their notebooks? We'd have to figure out a place to store those files though. (And maybe not a very common use case.) Anwyay, I say we make removing the Source button a separate issue and merge this PR.

**Review by hirokiterashima — APPROVED** [review]
Additional changes look good. Let's create new issue for the source problem.

**Pull request merged**
