### PR TITLE
Fix deprecated Hibernate Criteria methods that are used for WISE5

### LINKED ISSUE #851: Fix deprecated Hibernate Criteria methods that are used for WISE5
Hibernate's createCriteria and its associated methods have been deprecated as a result of upgrading to Hibernate 5.2: http://stackoverflow.com/questions/40720799/deprecated-createcriteria-method-in-hibernate

Fix the WISE5 database queries so we'll be future-proof. Leave the WISE4 database queries alone for now because we may remove all the WISE4 code in the future.

### PR DESCRIPTION
**Pull request by geoffreykwan**
Make sure all the WISE5 database queries still work properly like they did before. Test each function by performing the associated action in the site, vle, at, or cm that will trigger the database query.

Closes #851

### CODE REVIEW

**Comment by hirokiterashima** [comment]
- [ ] Found a new issue: as a teacher, create a new run and immediately open the classroom monitor for that run. CM never loads (you see a blank screen) and there's a java exception:

```
	at org.wise.portal.service.vle.impl.VLEServiceImpl$$FastClassBySpringCGLIB$$d3322afa.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
MethodProxy.java:218
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
CglibAopProxy.java:684
	at org.wise.portal.service.vle.impl.VLEServiceImpl$$EnhancerBySpringCGLIB$$223cb773.getRunStatusByRunId(<generated>)
	at org.wise.vle.web.RunStatusController.doGet(RunStatusController.java:95)
RunStatusController.java:95
```

**Comment by geoffreykwan** [comment]
Creating a run and immediately opening the Classroom Monitor should work now.

**Comment by hirokiterashima** [comment]
Change this:
```
    try {
      return query.setMaxResults(1).getSingleResult();
    } catch(NoResultException e) {
      return null;
    }
```

to this: 
```
    return query.getResultStream().findFirst().orElse(null);
```

**Comment by geoffreykwan** [comment]
Ok, I've made the changes to remove the try/catch code.

**Comment by hirokiterashima** [comment]
- [ ] Found a bug adding a run to a student.
1. Log in as a student and add a run. The new run will appear.
2. Refresh the page. The new run disappears.

**Pull request merged**
