### PR TITLE
Show posts from Discourse in teacher homepage

### LINKED ISSUE #2806: Show posts from discourse in Teacher Home
If discourse_url is specified in application.properties:
- Show 3 latest topics (new/updated) in the teacher home page. Each topic should be a link to open the topic in a new tab. Show the topic title, posters, and last modified time
- Show a link to open discourse in another tab, log in to discourse or create account via SSO.

### PR DESCRIPTION
**Pull request by hirokiterashima**
Note: needs styling from @breity

This PR will show up to 3 most recent topics from a linked Discourse site for the logged-in teacher.

### Set up: Discourse
1. Install Discourse with Docker by following instructions on this page: https://meta.discourse.org/t/beginners-guide-to-install-discourse-for-development-using-docker/102009. This will create the admin user.
2. Enable Cross-Origin Resource Sharing (CORS) for Discourse so that WISE can request for latest topics. In discourse/bin/docker/unicorn, add ```-e DISCOURSE_ENABLE_CORS='true'``` to the docker command.
```
...
docker exec -it -e DISCOURSE_ENABLE_CORS='true' -u discourse:discourse discourse_dev /bin/bash -c "$CMD"
```
3. Start Discourse by running ```d/unicorn -x``` and check that it's running at http://localhost:9292
4. Log in with the admin user that you created as part of step 1, and configure CORS and SSO settings

Specify CORS origin:
Screen Shot 2020-11-13 at 9 38 32 AM

Enable SSO:
Screen Shot 2020-11-13 at 9 39 00 AM

Specify SSO url and secret (the secret must match the setting in application.properties, which we'll get to later):
Screen Shot 2020-11-13 at 9 39 36 AM

### Set up: WISE
1. Link to the Discourse instance by setting properties in application.properties
```
discourse_url=http://localhost:9292
discourse_sso_secret_key=secret_handshake
```

### Test
1. Log in as a teacher user. In the teacher homepage, you should see a "Recent Posts in Teacher Community" section at the top of the page, listing up to three latest topics. There should also be an expand icon.
2. Click on the expand icon. This should open a new tab, and log you into Discourse using your WISE account.
3. Add a new topic in Discourse, and verify that the Recent Posts section updates and show the new topic at the top.
4. Log in as another teacher user. In the teacher homepage, click on a topic. It should take you to the topic page in Discourse (but not log you in yet). If you click on the 'reply' button, it should log you into Discourse using your WISE account.
5. Comment out the properties from application.properties, and restart. The "Recent Posts in Teacher Community" section should not appear.

Closes #2806

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
The main functionality of Discourse and SSO works well. Here are some minor things I noticed.

- The minimum topic name length and minimum post body length is kind of annoying. Is it possible to remove them?

- On the teacher home page, the "Welcome to Discourse" thread always shows up at the top of the recent posts even if there are newer posts. Should it move down the "recent posts" list if there are newer posts?

- Signing out of WISE does not sign you out of Discourse. Should it also sign you out of Discourse or invalidate your Discourse session?

**Comment by hirokiterashima** [comment]
> * The minimum topic name length and minimum post body length is kind of annoying. Is it possible to remove them?

You can configure this via Discourse Admin Settings -> search for "min post length" and "min topic title length"

> * On the teacher home page, the "Welcome to Discourse" thread always shows up at the top of the recent posts even if there are newer posts. Should it move down the "recent posts" list if there are newer posts?

I think this is because the topic is pinned. If you unpin it, it should go away. We can also programmatically remove this topic from appearing on the WISE end if we want the "Welcome to Discourse" thread to appear on wise-discuss, but not on teacher homepage.

> * Signing out of WISE does not sign you out of Discourse. Should it also sign you out of Discourse or invalidate your Discourse session?

This could be a bit tricky to implement. I don't see harm in letting users post on Discourse even after signing out from WISE. Discourse will also log them out after a period of inactivity.

**Review by geoffreykwan — APPROVED** [review]
> You can configure this via Discourse Admin Settings -> search for "min post length" and "min topic title length"

Should we set "min username length" to 2? We have WISE usernames with 2 characters.
Should we set "min topic title length" to 1?
Should we set "min first post length" to 1?
Should we set "min post length" to 1?

> I think this is because the topic is pinned. If you unpin it, it should go away. We can also programmatically remove this topic from appearing on the WISE end if we want the "Welcome to Discourse" thread to appear on wise-discuss, but not on teacher homepage.

Ok, that post was pinned globally and I just needed to unpin it globally.

> This could be a bit tricky to implement. I don't see harm in letting users post on Discourse even after signing out from WISE. Discourse will also log them out after a period of inactivity.

I guess that should be fine since teachers don't usually share computers.

**Review by breity — APPROVED** [review]
Looks good. 👍 
I updated the styling and layout.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
