### PR TITLE
Upgraded Spring 4 -> 5

### PR DESCRIPTION
**Pull request by hirokiterashima**
Make sure that:
1. As student, you can:
   1. log in with your existing password
   2. change your password and log in with the new password
   3. create a new student user and log in
   4. log in with a google account
2. As teacher, you can:
   1. log in with your existing password
   2. change your password and log in with the new password
   3. create a new teacher user and log in
   4. log in with a google account
3. Team sign in works and you can launch a run
4. WebSocket features still work: giving teacher feedback and discussion posts update in real-time.
5. Test out other parts of WISE that you think needs testing

### CODE REVIEW

**Comment by vkorir** [comment]
Bug: I am not able to create a new teacher account using email and passwd.  I get the html dump below

Screen Shot 2019-04-08 at 9 34 59 AM

**Comment by hirokiterashima** [comment]
@vkorir I could not reproduce your bug. Looks like an exception was thrown on the server side. Can you copy&paste stacktrace?

**Comment by vkorir** [comment]
@hirokiterashima I keep getting an exception `Username and Password not accepted.`

Screen Shot 2019-04-08 at 10 53 58 AM

**Comment by hirokiterashima** [comment]
@vkorir this was because your username/password for smtp was not correct. Set them in wise.properties, or set ```send_email_enabled=false```

I also just committed code to check for the send_email_enabled property so please pull before testing again.

**Comment by vkorir** [comment]
Looks good! ✔️

**Pull request merged**
