### PR TITLE
Extract advanced component authoring into pop-up

### LINKED ISSUE #2834: Extract advanced component authoring into pop-up
1. Move code for advanced component authoring into a separate component.
2. Show the advanced component as popup that appears when the author clicks on the "advanced" wrench icon.

### PR DESCRIPTION
**Pull request by geoffreykwan**
Make sure the advanced authoring for all the component types show up in the pop up and all the advanced authoring elements work.

Closes #2834

### CODE REVIEW

**Review by hirokiterashima — APPROVED** [review]
Looks good. 

I think the dialog can use simple styling touches, like making it take up a bigger portion of the screen. @breity, can you take a look?

**Comment by breity** [comment]
> Looks good.
> 
> I think the dialog can use simple styling touches, like making it take up a bigger portion of the screen. @breity, can you take a look?
Sure, I updated the styles and dialog width.

**Comment by hirokiterashima** [comment]
@breity can this PR be merged? If not, what still needs to be done?

**Comment by breity** [comment]
> @breity can this PR be merged? If not, what still needs to be done?

@hirokiterashima Yep, should be good to go. Can you do a quick re-review to make the style changes look good? I'll approve.

**Review by breity — APPROVED** [review]

**Comment by hirokiterashima** [comment]
New style changes look good! 👍

**Pull request merged**
