### PR TITLE
Convert Notebook to Angular

### LINKED ISSUE #2827: Convert Notebook to Angular
Convert the Notebook to an Angular component. This includes converting these sub components
- notebook
- notebook launcher
- notebook notes
- notebook item
- notebook report
- notebook report annotations

### PR DESCRIPTION
**Pull request by geoffreykwan**
Make sure these actions still work
- Student notebook opens
- Student can add a note (see screenshot below of how to get to the add note button)
- Student can edit a note
- Student report opens
- Student report saves changes
- Teacher report opens
- Teacher report saves changes
- Teacher can view student notebooks in Classroom Monitor
- Teacher can view student reports in Classroom Monitor

@breity Styling needs to be fixed for
- Notebook launch button
- Notebook add note button
- Notebook notes
- Report for teacher and student
- Teacher grading view of student notebooks

Also take a look at the html attributes in all the related html files and remove things that are no longer needed. I've also tried to remove notebook related files that are no longer needed but you should also take a look to see if there's more that can be deleted.

Right now when you open the Notebook, an overlay appears over the VLE content so you can't see it anymore. This also covers the Add Note button. To hide the overlay, you can edit the css in the browser by finding the <notebook-notes> element and setting display: none.

Screenshot 2020-12-11 171652 - Copy

Closes #2827

### CODE REVIEW

**Comment by hirokiterashima** [comment]
Functionality looks good. I'll test again once @breity fixes the UI issues. I cleaned up some code.

I also noticed that messages.xlf was not updated. The extract-i18n pre-commit script fails with errors like these:
```
ERROR in Can't bind to 'aria-label' since it isn't a known property of 'button'. ("f="isShowButton()" mat-button
    class="md-scale md-fab md-fab-bottom-right notebook-launcher"
    [ERROR ->]aria-label="{{ fabLabel() }}"
    matTooltip="{{ fabLabel() }}"
    matTooltipPosition="above"
")
```
Jon, can you take a look at fixing these too as you're fixing the UI?

**Comment by breity** [comment]
> I also noticed that messages.xlf was not updated. The extract-i18n pre-commit script fails with errors like these:
> 
> ```
> ERROR in Can't bind to 'aria-label' since it isn't a known property of 'button'. ("f="isShowButton()" mat-button
>     class="md-scale md-fab md-fab-bottom-right notebook-launcher"
>     [ERROR ->]aria-label="{{ fabLabel() }}"
>     matTooltip="{{ fabLabel() }}"
>     matTooltipPosition="above"
> ")
> ```
> 
> Jon, can you take a look at fixing these too as you're fixing the UI?

Yep, I'll fix those. Just involves correcting invalid HTML attributes.

**Review by breity — APPROVED** [review]
Okay, I refactored and removed the Notebook component. NotebookNotes and NotebookReport now extend the NotebookParent component. NotebookLauncher has been simplified.

I also updated/fixed styling and moved relevant styles from WISE5 `_notebook.scss` to the Angular components.

One thing I noticed: public notes don't work anymore. Students can mark a note as public in a run and the note moves to the public group locally in the client. But other students don't see the public note and the change doesn't persist when reloading. I think this may be an existing issue not related to the PR.

**Comment by hirokiterashima** [comment]
Looks good so far.

Public notebook seems to be working on develop, so it appears that it broke during this PR. I'll see if it can be fixed.

**Comment by hirokiterashima** [comment]
I did a bit more investigation and found that public notebook items were retrieved when the notebook was opened: https://github.com/WISE-Community/WISE/blob/develop/src/main/webapp/wise5/themes/default/notebook/notebook/notebook.js#L192-L221

These lines appear to be removed in this PR branch code. @breity can you see if you can add this back?

**Comment by breity** [comment]
Thanks @hirokiterashima. I re-enabled public notebook item retrieval.

I still some issues with the public notebook. Can't seem to remove an item from the public notebook, for example. But this looks to be occurring on develop as well, so likely an existing bug we can create a separate issue for.

**Review by hirokiterashima — APPROVED** [review]
Looks good! The public notes issue is fixed.

**Pull request merged**
