### PR TITLE
Unlinking Google account for teachers and students

### LINKED ISSUE #2870: Allow users to unlink Google accounts
Users (both students and teachers) can choose whether to sign in using Google or not when first creating a WISE account. Many existing users have requested to remove a linked Google account. We have to manually edit the database to do this now. We should support users in doing it themselves.

Designs:
Site_ Account Info (Google account)
Site_ Edit Password - Google account
Site_ Unlink Google account confirm
Site_ Unlink Google account - create password
Site_ Unlink Google account success

For teachers, send them a confirmation email with their new username.

### PR DESCRIPTION
**Pull request by hirokiterashima**
**Description**
Teachers and students can now unlink Google account from their WISE accounts. The prototypes for the unlinking sequence can be found on issue #2870. Teachers will get a confirmation email. The change should reflect immediately without refreshing, so that the unlink button will disappear and you can go directly to editing the password after unlinking the account.

@breity please style as needed. I could not figure out how to style the student form properly so that the bottom div with the buttons fill the entire width.

I've also cleaned up some code and added tests. I think we can extract common functions in teacher/student edit-profile component, but that should be done in a separate task.

**Testing**
For testing purposes, I found it useful to remember the googleUserId in the user_details table before unlinking it, so that you can re-set the google id with this query:
```
update `user_details` SET `googleUserId` = 'GOOGLE_ID' WHERE (`id` = 'USER_ID');
```

**Test for students and teachers**
- you can unlink the google account via edit profile and edit password pages
- you can still edit other profile values

**Additional test for teachers**
- an email is sent to the teacher with the confirmation

Closes #2870

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Most of the functionality works and looks good.

You can't unlink a teacher Google user from the "Account Info" tab. Sign in as a teacher Google user and go to the "Account Info" tab and click the "Unlink Google Account" button, it will fail and this error will show up in the Console

```
ERROR TypeError: ctx_r16.unlinkGoogleAccount is not a function
    at EditProfileComponent_ng_container_74_Template_button_click_3_listener (edit-profile.component.html:129)
```

I think the unlinkGoogleAccount() function is missing from the teacher edit-profile.component.ts file.

**Comment by hirokiterashima** [comment]
@geoffreykwan good catch. I must have removed it when I started and stopped extracting common functions in student and teacher to a parent component class. I added it back. Can you test again?

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Review by breity — APPROVED** [review]
Functionality works, looks good.

I styled the dialogs and the teacher/student edit profile pages.

**Pull request merged**
