### PR TITLE
Run prettier on .js and .ts files

### LINKED ISSUE #2241: Run prettier on .js and .ts files
### Description

Define the prettier rules and then run prettier on all our .js and .ts files.

### PR DESCRIPTION
**Pull request by brianmickel**
Add an npm package script to format all .js and .ts files.
Ignore third party and dist files via .prettierignore.
Remove vscode setting json from .prettierrc.json
Format all .js and .ts files via `npm run format:all`

No change in app behavior expected

Resolves #2241

### CODE REVIEW

**Comment by brianmickel** [comment]
Hi, I'm looking forward to contributing to this project so I picked an easier issue to get started with.
This PR would be a painful change if merged before other outstanding changes/branches because of the conflicts. If it meets approval standards, I recommend we wait until a lull in in progress work to prevent conflicts.
We also need to improve the prettier rules over time to match the intended goals of the core maintainers.

**Comment by brianmickel** [comment]
#2296

**Comment by hirokiterashima** [comment]
Hi @brianmickel thanks for working on this task! We'll take a look once we review outstanding PRs. We look forward to your future contributions.

**Comment by hirokiterashima** [comment]
Hi @brianmickel, apologies for the late reply. We've been making a lot of changes to the codebase since you made this PR.

Are you still interested in helping us out with the prettier issue? If you are, can you please work off of the latest code in the ```develop``` branch and make a new PR to match the updated description in issue #2241? We realized that we only need prettier to be run on the site directory for now. This will also make it easier for us to review your changes.

Thanks so much!

**Pull request closed without merging**
