### PR TITLE
fixed issue creating duplicate workgroup on accident

### LINKED ISSUE #1905: Students can create duplicate workgroups on accident
### Description

1. Student aa0101 launches the project and gets to the classmate sign in page on computer 1.
2. Student bb0101 launches the project and gets to the classmate sign in page on computer 2.
3. Student aa0101 adds bb0101 as a teammate.
4. Student bb0101 adds aa0101 as a teammate.
5. Student aa0101 clicks "Launch Unit"
6. Student bb0101 clicks "Launch Unit"
7. Two workgroups are created and both workgroups contain aa0101 and bb0101.

What should happen
Only one workgroup should be created that contains aa0101 and bb0101.

### PR DESCRIPTION
**Pull request by vkorir**
1. login as student aa0101, add unit XYZ and get to the team sign in page on browser1 
2. login as student bb0101, add unit XYZ and get to the team sign in page on browser2
3. aa0101 adds bb0101 as teammate
4. bb0101 adds aa0101 as teammate
5. aa0101 clicks 'Launch Unit'
6. bb0101 clicks 'Launch Unit'
- verify that aa0101 and bb0101 belong to the same workgroup
7. login as cc0101, add unit XYZ, get to the team sign in page and add aa0101 as teammate
- verify that bb0101 also shows up on the list of teammates
8. complete adding bb0101 to the team and cc0101 clicks 'Launch Unit'
- verify that cc0101 is added to aa0101 and bb0101 workgroup
9. login as dd0101, add XYZ, get to the team sign in page and add aa0101 as teammate
- verify that you get an error saying aa0101 belong to a team that is full
10. verify that it this also works for students with google accounts

closes #1905

### CODE REVIEW

**Comment by geoffreykwan** [comment]
We now handle these two additional scenarios

1.
In a new run
Browser 1 sign in as aa0101 and add bb0101. Do not click launch yet.
Browser 2 sign in as bb0101 and add cc0101 and dd0101. Do not click launch yet.

Browser 1 click launch. The project should be launched.
Browser 2 click launch. The project should not be launched. It should say bb0101 is already in a workgroup with aa0101. It should remove cc0101 and dd0101 and then add aa0101.

2.
In a new run
Browser 1 sign in as aa0101 and add bb0101. Do not click launch yet.
Browser 2 sign in as cc0101 and add dd0101 and aa0101. Do not click launch yet.

Browser 1 click launch. The project should be launched.
Browser 2 click launch. The project should not be launched. It should say aa0101 is already in a workgroup. It should remove aa0101.

**Comment by vkorir** [comment]
@breity 
that's the expected behavior, bb0101 is added to the workgroup that has aa0101 and cc0101 instead of creating a new one. the only thing that GK and i were wondering is whether we should ask cc0101 to sign in before launching again (we were going to create a new issue for this).

**Comment by breity** [comment]
@vkorir Ah sorry, I missed a step in the comment above (https://github.com/WISE-Community/WISE/pull/1906#pullrequestreview-250782374). Just added it in now in bold.

**Comment by breity** [comment]
@vkorir Edit: sorry again. That was a false alarm. Looks like my code hadn't updated completely when testing. Looks like this is working properly. Thanks!

**Pull request merged**
