### PR TITLE
Refactored code in projectController 

### LINKED ISSUE #2576: Refactor ProjectController.ts
1. Duplication: methods previewProject() and previewProjectWithoutConstraints() are similar
1. Remove $stateParams.projectId and get it from ConfigService.projectId()
1. Remove unused methods ```projectHomeClicked```, ```projectTitleChanged```
1. Remove unused variable ```showTemplateChooser```
1. Remove unused code
```
 this.$rootScope.$on('$stateChangeSuccess', (event, transition) => {
    this.scrollToBottomOfPage();
 });
```

### PR DESCRIPTION
**Pull request by hirokiterashima**
Removed unused variables/methods/comments, and combining methods. I also removed AngularJS constructs like $rootScope, $anchorScroll, and $stateParams.

Test the following in the Authoring Tool:
- loading units
- canceling createNode/createGroup
- previewing with/without constraints

Closes #2576

### CODE REVIEW

**Comment by geoffreykwan** [comment]
You removed cancelCreateGroupClicked() and cancelCreateNodeClicked() and replaced them with direct calls to toggleView("project") but should we be doing that? It seems less modular if you call toggleView("project") directly.

**Comment by hirokiterashima** [comment]
I think this extra level of indirection is not necessary because the functions are not doing anything beside calling toggleView('project'). Saying 
```
ng-click='projectController.toggleView("project")'
```
in the template will describe the expected behavior of the button more directly and makes the code easier and quicker to understand.

In the future, if we want the button click to do more than just toggleView('project'), we can create a function.

**Comment by hirokiterashima** [comment]
I replaced toggleView("project") with showProjectView(). This is more precise description for the actual behavior when the button is clicked.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
